//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoGiaoHangNhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiaoHang()
        {
            this.LichSuGiaoHangs = new HashSet<LichSuGiaoHang>();
        }
    
        public int Id { get; set; }
        public int IdDonHang { get; set; }
        public int IdXe { get; set; }
        public string TrangThai { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual Xe Xe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuGiaoHang> LichSuGiaoHangs { get; set; }
    }
}
