//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoGiaoHangNhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuVuc
    {
        public int Id { get; set; }
        public int IdNhanVienGiaoHang { get; set; }
        public string Ten { get; set; }
        public string ToaDo { get; set; }
        public Nullable<double> KhoangCach { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
