//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoGiaoHangNhanh.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyKhoGiaoHangEntities10 : DbContext
    {
        public QuanLyKhoGiaoHangEntities10()
            : base("name=QuanLyKhoGiaoHangEntities10")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BanGiaoVatTu> BanGiaoVatTus { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<GiaoHang> GiaoHangs { get; set; }
        public virtual DbSet<KhuVuc> KhuVucs { get; set; }
        public virtual DbSet<LichSuBanGiaoVatTu> LichSuBanGiaoVatTus { get; set; }
        public virtual DbSet<LichSuGiaoHang> LichSuGiaoHangs { get; set; }
        public virtual DbSet<LichSuPhanPhoi> LichSuPhanPhois { get; set; }
        public virtual DbSet<LoiNhanVien> LoiNhanViens { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<VatTu> VatTus { get; set; }
        public virtual DbSet<Xe> Xes { get; set; }
    }
}
