//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhoGiaoHangNhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.BanGiaoVatTus = new HashSet<BanGiaoVatTu>();
            this.KhuVucs = new HashSet<KhuVuc>();
            this.LichSuBanGiaoVatTus = new HashSet<LichSuBanGiaoVatTu>();
            this.LichSuPhanPhois = new HashSet<LichSuPhanPhoi>();
            this.LoiNhanViens = new HashSet<LoiNhanVien>();
            this.TaiKhoans = new HashSet<TaiKhoan>();
            this.Xes = new HashSet<Xe>();
        }
    
        public int Id { get; set; }
        public string TenNhanVien { get; set; }
        public string ThuongTru { get; set; }
        public string Sdt { get; set; }
        public string Gmail { get; set; }
        public string Khoi { get; set; }
        public Nullable<decimal> Luong { get; set; }
        public System.DateTime NgayBatDauLam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanGiaoVatTu> BanGiaoVatTus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhuVuc> KhuVucs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuBanGiaoVatTu> LichSuBanGiaoVatTus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuPhanPhoi> LichSuPhanPhois { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoiNhanVien> LoiNhanViens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoan> TaiKhoans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Xe> Xes { get; set; }
    }
}
